### ISSUE TITLE
Wrong message when incorrectly specify the browser in the property 

### ISSUE THREAD

**Issue by markeloff86** [sbtqa/page-factory#102]
When I incorrectly specify name of browser in the properties file, I get " '' is not support yet". 
![photo_2018-01-31_19-07-56](https://user-images.githubusercontent.com/18211389/36196674-af9851c0-119b-11e8-93b3-54c622bcf3a6.jpg)

**Comment by kosteman** [comment]
Can you provide next information
1. page-factory version
2. your application.properties file with incorrectly specified name of browser

**Comment by markeloff86** [comment]
1.4.14 
browser.name = Chrome
required key is webdriver.browser.name

**Comment by kosteman** [comment]
Ok.
We will add presence verification of all required properties

**Comment by markeloff86** [comment]
@kosteman where can I look at all the required properties?

**Comment by kosteman** [comment]
all optional parameters have #optional comment. all others - required.
You can ask me about every single parameter via the direct messages
