### ISSUE TITLE
Bad regexp in openPage step

### ISSUE THREAD

**Issue by imixac** [sbtqa/page-factory#103]
When I create a step "@Когда("^открывается страница \"(.*?)\" и ожидает элемент \"(.*?)\"$")" in my stepdefinitions and used in feature:

```
ru.sbtqa.tag.qautils.errors.AutotestError: Page object with title 'Стартовый менеджер" и ожидает элемент "Поиск по каталогу' is not registered
                at ru.sbtqa.tag.pagefactory.PageWrapper.getPage(PageWrapper.java:54)
                at ru.sbtqa.tag.pagefactory.stepdefs.GenericStepDefs.openPage(GenericStepDefs.java:218)
```

**Comment by SandraBarmina** [comment]
This isn't a problem of Page-Factory. don't need to use keywords "открывается страница" in your steps. 
This step breaks the work in bdd-editor, so you need to rewrite it in the library ufsui-webdriver

**Comment by 0I0u3uk** [comment]
Why you close this task? I think we should rewrite regexp.
