### ISSUE TITLE
Multithreading (multiple instances of the webdriver)

### ISSUE THREAD

**Issue by Harmattan322** [sbtqa/page-factory#121]
On projects with multiple tests (more than 1000), according to DevOps, it will not be possible to quickly run these tests (previously used for the run of regression tests almost all night). For this reason, I would like to create several instances of a webdriver, and not just one. Was it in the plans (pf-2?)?

**Comment by clicman** [comment]
Yes. PF2 will fully support of parallel test run. Subscribe to https://github.com/sbtqa/page-factory-2/issues/31 to be up to date.
