### ISSUE TITLE
Incorrect allure cucumber jvm plugin version

### ISSUE THREAD

**Issue by Harmattan322** [sbtqa/page-factory#123]
Use: **allure-cucumber2-jvm** instead allure-cucumber-jvm (issue of allure 2):
https://github.com/allure-framework/allure2/issues/731.

Perhaps this will solve the problem associated with incorrect json file names.
As a result, problems may be solved:
1) long script names do not allow these scenarios to get into the report (however they are launched);
2) the special characters in the script name do not allow this test to even start (errors do not occur, it is difficult to notice this bug).

**Comment by Harmattan322** [comment]
correction:
1. long path to .json file + scripts names (because of an incorrect .json file name) do not allow these scenarios to get into the report (however they are launched);
for example, locally the test will pass to the report, but in jenkins at run in the docker - no. At this point "solution" would be to reduce the script name in the feature...

**Comment by Harmattan322** [comment]
Solution: https://github.com/allure-framework/allure-java/issues/130

**Comment by Harmattan322** [comment]
opened a new issue for them: https://github.com/allure-framework/allure-java/issues/214

**Comment by kosteman** [comment]
page-factory-1.9.2 is using allure-cucumber2-jvm now

**Comment by Harmattan322** [comment]
@kosteman, using page-factory 1.9.2:
cucumber.runtime.CucumberException: 

gherkin.ParserException$CompositeParserException: Parser errors:
(1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '# language: ru'
(3:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Функционал: Пилот АФТ Е2Е сценария'

Does not recognize the Russian language (and '# language: ru' or '#Language:ru')?

**Comment by clicman** [comment]
@kosteman why is pf1 using cucumber2? it should be pf2 feature only!

**Comment by kosteman** [comment]
cant reproduce on page-factory-example (tried on 9499f2d7710aaa30533d13ca3122bb08d50ab97a revision)

**Comment by kolyas-github** [comment]
@kosteman, when I set version of page-factory on 1.9.2, I got error 
"java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType()Lcom/fasterxml/jackson/databind/JavaType". 
Then I add dependency jackson-databind(version - 2.9.5) - that is all right.
Is it right?

**Comment by kosteman** [comment]
@kolyas-github create another issue about it please.
And send me a details on my email.

**Comment by Harmattan322** [comment]
@kosteman, there was a problem of the encoding:
after removing the feature and creating exactly the same again - all ok. Thx.
