### ISSUE TITLE
Test steps not displayed in IDEA.

### ISSUE THREAD

**Issue by mvi358** [sbtqa/page-factory#148]
Начиная с версии 1.9.0, перестали отображаться шаги выполнения теста в IDEA. IDEA версии 2017.3.4

Пример:
Версия 1.12.1
![1](https://user-images.githubusercontent.com/43003638/45162019-983f3200-b1dc-11e8-9334-9cf74de19b4c.jpg)
Версия 1.8.1
![2](https://user-images.githubusercontent.com/43003638/45162097-bc027800-b1dc-11e8-89d3-b1088807c5b5.jpg)

**Comment by MeSaNei** [comment]
Плюсую. Актуально и для page-factory-2

чт, 6 сент. 2018 г. в 17:04, mvi358 <notifications@github.com>:

**Comment by clicman** [comment]
Мы обновили cucumber-jvm до версии 2.4, и с ним так работает плагин идеи. Если хотите видеть степы, то запускайте не CucumberTest, а файл фичи или даже папку с фичами, тогда будут отображены степы.
