### ISSUE TITLE
Update versions dependencies in pom

### ISSUE THREAD

**Issue by 0I0u3uk** [sbtqa/page-factory#15]
Hi guys.
I downloaded your project and saw this situation in pom. 
![image](https://cloud.githubusercontent.com/assets/1384046/22025025/af2521c8-dcfe-11e6-9092-5716ecce6b12.png)

I think you should update pom to correct versions your projects

**Comment by clicman** [comment]
Hi! We on the way to downgrade to java7 and masters are destructed for now. Wait until @kosteman merges https://github.com/sbtqa/page-factory/pull/14 and https://github.com/sbtqa/monte-media/pull/1
When it happens all automaticully wil up.

**Comment by clicman** [comment]
Just add following to your settings.xml:
```
 <repositories>
        <repository>
          <id>snapshots-repo</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
```

See https://github.com/sbtqa/page-factory/blob/master/.travis/settings.xml for example

**Comment by 0I0u3uk** [comment]
Thanks it help me.
