### ISSUE TITLE
Отключение Welcome page Chrome в Android

### ISSUE THREAD

**Issue by max-scald** [sbtqa/page-factory#156]
При запуске каждого автотеста через Appium в Chrome появляется страница приветствия в следствии чего приходится в каждом тесте использовать предысторию из десятка шагов для закрытия всех окон и обхода HTTPS безопасности. 
Предлагаю добавить две capabilities "noReset": true и "fullReset": false
Документация по ним здесь http://appium.io/docs/en/writing-running-appium/other/reset-strategies/index.html

**Comment by max-scald** [comment]
Прошу принять к рассмотрению мои дополнения к фреймвёрку #157

**Comment by clicman** [comment]
Привет! Спасибо за пр! Завтра обязательно посмотрим.

**Comment by clicman** [comment]
И свяжись со мной по почте плз. clicman@yandex.ru

**Comment by clicman** [comment]
@max-scald проверь плз page-factory-1.16.0. И если все ок, то тикет надо закрывать.
