### ISSUE TITLE
Не работает Aspectj Step

### ISSUE THREAD

**Issue by Sergo101010100** [sbtqa/page-factory#159]
При встраивании этого фрэймворка в проект с junit-тестами (например,  https://github.com/allure-examples/allure-junit-example)  перестает работать формирование @io.qameta.allure.Step (через аспект io.qameta.allure.aspects.StepsAspects)  в Allure.

Прошу подсказать каким образом page-factory блокирует работает аспектов

**Comment by clicman** [comment]
Хммм... а page-factory-2?

**Comment by Sergo101010100** [comment]
C page-factory-2 тоже.
Без зависимости 
![image](https://user-images.githubusercontent.com/48100063/53679543-b9da2b80-3cde-11e9-8e41-b6338ba24c7e.png)
С зависимостью

 `<dependency>
            <groupId>ru.sbtqa.tag.pagefactory</groupId>
            <artifactId>web-plugin</artifactId>
            <version>10.0.0</version>
        </dependency>`

![image](https://user-images.githubusercontent.com/48100063/53679556-fad24000-3cde-11e9-8cf9-299235b900bd.png)

**Comment by clicman** [comment]
Судя по всему, что-то не так с конфигурацией.
Я сделал [ветку](https://github.com/sbtqa/page-factory-2-example/tree/junit-steps-example) с примером рабочей конфигурации.
Надо запуситить командой mvn test и получить отчет:
![image](https://user-images.githubusercontent.com/1079535/53679957-aa6ed880-3d06-11e9-80cb-371e72c768b7.png)


P.S. На данный момент работа с junit без cucumer находится в статусе MVP. Как только мы закончим работу над этой фичей, то в отчет будут автоматически добавляться шаги при вызовах методов типа openPage или click с нужными параметрами и логами.

**Comment by Sergo101010100** [comment]
Спасибо за помощь! 

Интересно что с page-factory-1 работает если добавить в argLine ` -Dcucumber.options="--plugin io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm --plugin pretty"` - тоже работает.

**Comment by Sergo101010100** [comment]
Так, а если для page-factory-1 ? Текущий проект именно на нем, а перейти слишком сложно.

**Comment by clicman** [comment]
Так. Миграция вообще простая. Переводили проекты за 1 день очень большие. 
Мы в pf1 только багфиксы делаем и новый функционал не предоставляем всех агитируя переходить на pf2

**Comment by Sergo101010100** [comment]
А это нельзя считать дефектом? :)

**Comment by clicman** [comment]
Нет. Pf1 это cucumber only фреймворк.
