### ISSUE TITLE
Add ability to invoke the fisrt webDriver.get method by yourself

### ISSUE THREAD

**Issue by varivoda** [sbtqa/page-factory#22]
This ability allows you control the moment when initial web page will be opened.
In this way we can easily construct tests which consist of several parts (swing, web, rest).

Ex: 
* user open swing application
...  // swing steps
* user open initial web page
... //web steps

Also we will be able to move the http-auth logic from createWebDriver to new step. 

* user open initial web page with http-auth

**Comment by 0I0u3uk** [comment]
Ok, I think we can close this issue
