### ISSUE TITLE
Implement several step definition classes

### ISSUE THREAD

**Issue by iamanikeev** [sbtqa/page-factory#5]
Need to put several classes with common step definitions:
- searchers (elements, clocks, lists)
- property checkers (find element, find out what type it is, check its properties, like visibility or availability)
- interactions (find element of particular type, perform action specific to only that type)
- table actions

Maybe this should even be a separate package, not sure

**Comment by clicman** [comment]
Do not forget to implement i18n framework for stepdefs.

**Comment by kosteman** [comment]
I think we can close this issue bacause of #10 and #20
