### ISSUE TITLE
Add property for working with aspects

### ISSUE THREAD

**Issue by 0I0u3uk** [sbtqa/page-factory#52]
Now we can disable aspects only through the method setAspectsDisabled(). I think we should add new property to application.properties for work with it.

**Comment by clicman** [comment]
It should be possible to manage this parameter  at runtime.
пт, 12 мая 2017 г. в 10:41, Svetlakov Anton <notifications@github.com>:

**Comment by kosteman** [comment]
I think we should support both this options
