### ISSUE TITLE
Uncorrect return value of TagWebdriver.getBrowserName()

### ISSUE THREAD

**Issue by kolyas-github** [sbtqa/page-factory#83]
Class DesiredCapabilitiesParsaer can't parse my properties because I have a property line equals "webdriver.**ie**.capability.nativeEvents" but TagWebdriver.getBrowserName() always return a full name of Internet Explorer "internet explorer". 

And then I getting "webdriver.**internet explorer**.capability.someCapability" it fail my parse process.

**Comment by 0I0u3uk** [comment]
I create pull request when we merge it use
webdriver.iexplore.capability.nativeEvents=true its should work
