### ISSUE TITLE
Implement support Allure2

### ISSUE THREAD

**Issue by dm-test** [sbtqa/page-factory#91]
Allure 2 is very usefull framework and we need to use it in our project.
Please, implement support of this fremework to Page-factory.
Thank you.

**Comment by 0I0u3uk** [comment]
@clicman can you give more information about task? 
where are we should add supporting? In https://github.com/sbtqa/allure-helper/tree/master/src/main/java/ru/sbtqa/tag/allurehelper ?

**Comment by clicman** [comment]
Yes, just extend another listener and try it out. Maybe it can works as is.

**Comment by 0I0u3uk** [comment]
Also we should check than @Issue="name" will be work by default

**Comment by 0I0u3uk** [comment]
@kosteman can we close this issue?

**Comment by kosteman** [comment]
implement in 1.6.x
