### ISSUE TITLE
ChromeDriver crashes

### ISSUE THREAD

**Issue by oshmelev** [sbtqa/page-factory#92]
Class: TagWebDriver
Line 134: webDriver.manage().window().maximize();

Кучу дефектов в интернете что так он будет падать, если еще не было перехода по URL.
(и он таки падает)

Рекомендуемый способ максимайза для хром:
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.addArguments("--start-maximized");
driver = new ChromeDriver(chromeOptions);

**Comment by clicman** [comment]
👍

**Comment by senin24** [comment]
@clicman в application.properties-sample есть в конце строчка, которая решает эту проблему:
webdriver.chrome.capability.options.args=user-data-dir=C:\\workspace\\user-data\\,**start-maximized**

но может ее повыше перенести и написать, что "start-maximized" - это обязательный параметр?

**Comment by reb33** [comment]
вставили строчку в application.properties, проблема решилась

**Comment by clicman** [comment]
@senin24 да. Где-то ранее пронесли. Этот закрываю.
