### ISSUE TITLE
Error in Page.Core.findBlocks(String blockPath, Object context, boolean returnFirstFound)

### ISSUE THREAD

**Issue by reb33** [sbtqa/page-factory#96]
Class: Page
Line 1044: found.addAll(findBlocks(blockPath, currentField.get(context), returnFirstFound));

Перед рекурсией надо вставить currentField.setAccessible(true);
иначе падает с ошибкой IllegalAccessException

**Comment by 0I0u3uk** [comment]
Да, действительно упустили этот момент, поправил

**Comment by reb33** [comment]
А вы могли бы выгрузить изменения в maven?

**Comment by kosteman** [comment]
завтра в течении дня изменения появятся в центральном репозитории в версии 1.4.17

**Comment by 0I0u3uk** [comment]
@reb33 удалось проверить? все ок?

**Comment by reb33** [comment]
Да, проверил, дефект не воспроизводится
